### ISSUE TITLE
FHIR -> CDA: missing author.time

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#33]
CDA requires the **Timestamp of the authorship** (author.time), see [spec](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.9.23&effectiveDate=2019-09-12T13:48:28&language=en-US).

The mapping doesn't work for this example:

- [PADV-CANCEL.json](https://github.com/hl7ch/cda-fhir-maps/blob/additionalExamples/input/ch-emed/PADV-CANCEL.json)
   - https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.1352548

**Comment by oliveregger** [comment]
The problem here is that the practitioner is not provided. The example has a reference to https://example.ch/PractitionerRole/Pharma but in this resource there is no reference to a Practitioner and the CDA author time and assignedAuthor are not there.

An author must be enforced, even if a PractitionerRole is provided.

**Comment by oliveregger** [comment]
https://github.com/ehealthsuisse/ch-emed/issues/80
